# -*- coding: utf-8 -*-
"""Copy of Python Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nIDQsXJxhhNygXDnsBPxG6imsp1Lxf9u

*Q1.  Given a list of lists, write a Python program to count the number of lists contained within the list of lists.*

Examples:

Input :  [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

Output : 3
"""

input = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
print(len(input))

"""*Q2.  Given a list of strings, write a Python program to convert each element of the given list into a sublist. Thus, converting the whole list into a list of lists.*

Examples:

Input : ['alice', 'bob', 'cara']

Output : [['alice'], ['bob'], ['cara']]
"""

#solution
input = ['alice', 'bob', 'cara']
output = list() 
temp = list()
for x in input:
    output.append([x])
print(output)