# -*- coding: utf-8 -*-
"""Python Pattern Program Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FhYl4GvRHLjfgjpNUirucoPs-V8aw-Zb

1.Write a Python program which prints Unique Pyramid Pattern of Digits.

Pattern:


1 

1 2 1 

1 2 3 2 1 

1 2 3 4 3 2 1 

1 2 3 4 5 4 3 2 1
"""

N=5
for num in reversed(range(N )) : 
	  for x in range()

"""2.Write a Python program which prints inverted Pyramid of numbers.

Pattern:


1 1 1 1 1 

2 2 2 2 

3 3 3 

4 4 

5
"""

#write your code here
n=6
temp = n
for x in range(1,n+1):
    for _ in range(0,temp):
        print(x, end=' ')
    print('\n')
    temp = temp-1